version: '3.8'

services:
  # MySQL Database Service
  mysql:
    build: .
    container_name: ecobazaardb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecobazaar_db
      MYSQL_USER: ecobazaar_user
      MYSQL_PASSWORD: ecobazaar_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecobazaar-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 60s

volumes:
  mysql_data:
    driver: local

networks:
  ecobazaar-mysql-network:
    driver: bridge
